name: Build (Windows)

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/get-vcpkg-action@v2
        with:
          vcpkgCommitMessage: "setup"

      - name: Install dependencies (vcpkg)
        run: |
          vcpkg install curl:x64-windows
          vcpkg install nlohmann-json:x64-windows
          vcpkg install sqlite3:x64-windows

      - name: Configure (CMake)
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        shell: cmd

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
        shell: cmd

      - name: Upload artifacts (Release)
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: dicksuck-windows-msvc-${{ github.sha }}
          path: build/Release/dicksuck.exe
          retention-days: 14
